version: '3.8'

services:
  gateway-service:
#    IMAGE_APP_REGISTRY_URL=gitlab2....-software.local:4567/oleh.malko/assets-manager docker-compose up
#    image: ${IMAGE_APP_REGISTRY_URL}/gateway-service:latest
    build:
      context: gateway-service
      target: production
      dockerfile: Dockerfile
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
    networks:
      - assets-manager-network
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
  user-service-db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=user-service-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - assets-manager-network
  user-service:
#    image: ${IMAGE_APP_REGISTRY_URL}/user-service:latest
    build:
      context: user-service
      target: production
      dockerfile: Dockerfile
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
      - gateway-service
      - user-service-db
    networks:
      - assets-manager-network
    ports:
      - "8083:8083"
    volumes:
      - ./:/app
  assets-service-db:
    image: postgres:15.2-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=assets-service-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - assets-manager-network
  assets-service:
#    image: ${IMAGE_APP_REGISTRY_URL}/assets-service:latest
    build:
      context: assets-service
      target: production
      dockerfile: Dockerfile
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
    depends_on:
      - consul
      - gateway-service
      - assets-service-db
    networks:
      - assets-manager-network
    ports:
      - "8082:8082"
    volumes:
      - ./:/app
  consul:
    image: consul:1.14.3
    networks:
      - assets-manager-network
    ports:
      - "8500:8500"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - assets-manager-network

networks:
  assets-manager-network:
