server:
  port: 8081

spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: assets-service
          uri: lb://assets-service
          predicates:
            - Path=/assets/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/.well-known/jwks.json
          filters:
            - StripPrefix=0

# Security configuration
security:
  jwt:
    issuer: assets-manager
    audience: assets-manager-client
    jwk-set-uri: http://auth-service:8080/.well-known/jwks.json

logging:
  level:
    root: info
    com.gatewayservice: debug
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      #      for spring boot runner use localhost
      #      endpoint: http://localhost:9411/api/v2/spans
      #      for docker compose use zipkin
      endpoint: http://zipkin:9411/api/v2/spans