server:
  port: 8081

spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: assets-service
          uri: lb://assets-service
          predicates:
            - Path=/assets/**