server:
  port: 8083

spring:
  application:
    name: user-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}:${random.int[1,99]}

  datasource:
    driverClassName: org.postgresql.Driver
#   jdbc:postgresql://localhost:5432/user-service-db - for spring boot runner
#   jdbc:postgresql://user-service-db/user-service-db - for docker compose
    url: jdbc:postgresql://localhost:5432/user-service-db
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision_id
            revision_type_field_name: revision_type
    generate-ddl: false
    database: postgresql
    hibernate:
      ddl-auto: none

  flyway:
    table: schema_version
    locations: classpath:db/migration