server:
  port: 8082

spring:
  application:
    name: assets-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}:${random.int[1,99]}

  datasource:
    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5433/assets-service-db - for spring boot runner
#    url: jdbc:postgresql://assets-service-db/assets-service-db - for docker compose
    url: jdbc:postgresql://assets-service-db/assets-service-db
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision_id
            revision_type_field_name: revision_type
    database: postgresql
    hibernate:
      ddl-auto: none

  flyway:
    table: schema_version
    locations: classpath:db/migration

  # File upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      # Asset photos upload directory
      location: ./uploads/asset-photos

logging:
  level:
    root: info
    org.springframework: info
    com.assetsservice: debug
    # Add security-related logging
    org.springframework.security: info
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      #      for spring boot runner use localhost
      #      endpoint: http://localhost:9411/api/v2/spans
      #      for docker compose use zipkin
      endpoint: http://zipkin:9411/api/v2/spans